services:
  # Network Settings
  gluetun:
    image: ghcr.io/qdm12/gluetun
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Common
      - "8888:8888/tcp"   # HTTP proxy
      - "8388:8388/tcp"   # Shadowsocks
      - "8388:8388/udp"   # Shadowsocks
      # qBittorrent
      - "8081:8081"       # Web Interface
      - "6881:6881"       # TCP Port for Torrents
      - "6881:6881/udp"   # UDP Port for Torrents
      # Prowlarr
      - "9696:9696"       # Web Interface
      # Jackett
      - "9117:9117"       # Web Interface
      # Sonarr
      - "8989:8989"       # Web Interface
      # Radarr
      - "7878:7878"       # Web Interface
      # Lidarr
      - "8686:8686"       # Web Interface
      # Readarr
      - "8787:8787"       # Web Interface
      # Bazarr
      - "6767:6767"       # Web Interface
      # Jellyseerr
      - "5055:5055"       # Web Interface
      # Jellyfin
      - "8096:8096/tcp"   # Web Interface
      - "7359:7359/udp"   # Auto Discovery
      - "1900:1900/udp"   # DLNA/UPnP
    volumes:
      - ${ARRPATH}gluetun/config:/gluetun
      - ${ARRPATH}gluetun/config/wg0.conf:/gluetun/wireguard/wg0.conf
    env_file:
      - ./.env

  # Download Managers (Torrent)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}downloads:/downloads
    environment:
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    env_file:
      - ./.env

  # Indexers
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}prowlarr/config:/config
      - ${ARRPATH}prowlarr/backup:/data/backup
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jackett/data:/config
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env

  # Media Management (Movies and Series)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}sonarr/config:/config
      - ${ARRPATH}sonarr/backup:/data/backup
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}radarr/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}radarr/backup:/data/backup
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env
  
  # Music Management
  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: lidarr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}lidarr/config:/config
      - ${ARRPATH}music:/music
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env
  
  # Book Management
  readarr:
    image: ghcr.io/hotio/readarr:latest
    container_name: readarr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}readarr/data:/config
      - ${ARRPATH}books:/books
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env

  # Subtitle Management
  bazarr:
    image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}bazarr/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
    env_file:
      - ./.env

  # Request Management
  # Unified Requests for Movies and TV Shows
  # Connects with Sonarr, Radarr, Lidarr, Readarr, and Plex/Jellyfin
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jellyseerr/config:/app/config
    env_file:
      - ./.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  # Multimedia Streaming Servers
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jellyfin/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}downloads:/downloads
    env_file:
      - ./.env

